Repository GoogleCloudPlatform/cloud-opensource-java, pull requests merged in 2019-10, with the labels that each got.

#947 Fix release script bug when next version is supplied
  scripts/prepare_release.sh
Labels: cla: yes

#949 Release libraries-bom 2.5.0
  boms/cloud-oss-bom/pom.xml
  boms/upper-bounds-check/pom.xml
Labels: cla: yes

#952 add privacy policy link iff we turn on analytics
  docs/_layouts/default.html
Labels: best practices, cla: yes

#948 Add instructions for cleanup following an aborted release
  boms/cloud-oss-bom/RELEASING.md
Labels: cla: yes

#951 expand discussion of dependency scope
  docs/JLBP-1.md
Labels: cla: yes

#956 add cookie notice
  docs/_layouts/default.html
Labels: cla: yes

#903 use paragraphs for top level items, not lists JLBP-4
  docs/JLBP-4.md
Labels: cla: yes

#912 use paragraphs for top level items, not lists JLBP-15
  docs/JLBP-15.md
Labels: cla: yes

#958 latest google-cloud-java
  boms/cloud-oss-bom/pom.xml
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
  linkage-monitor/src/test/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitorTest.java
Labels: cla: yes

#961 Release libraries-bom 2.6.0
  boms/cloud-oss-bom/pom.xml
  boms/upper-bounds-check/pom.xml
Labels: cla: yes

#962 don't use Google Maven Central mirror
  kokoro/continuous.sh
  settings.xml
Labels: cla: yes

#963 Release script to use suffix to distinguish release items
  boms/cloud-oss-bom/RELEASING.md
  scripts/prepare_release.sh
Labels: cla: yes

#954 Better failure message for characterization test
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
Labels: Testing, cla: yes

#927 Added "view on GitHub" link
  docs/_layouts/default.html
Labels: blocked, cla: yes

#974 Setting generateBackupPoms=false
  scripts/prepare_release.sh
Labels: cla: yes

#972 Improve on the error message of Truth.containsExactlyElementsIn
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
Labels: cla: yes

#975 update to latest google-cloud-java 0.116.0
  boms/cloud-oss-bom/pom.xml
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
Labels: cla: yes

#976 Release preparation for BOM 2.7.0
  boms/cloud-oss-bom/pom.xml
  boms/upper-bounds-check/pom.xml
Labels: cla: yes

#959 track Google Analytics
  docs/_config.yml
  docs/_layouts/default.html
Labels: cla: yes

#894 add cloud logo
  docs/_layouts/default.html
  docs/assets/css/style.css
Labels: cla: yes

#982 Fix config syntax error
  docs/_config.yml
Labels: cla: yes

#983 Linkage monitor error to include dependency path to problematic artifacts
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java
  linkage-monitor/src/main/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitor.java
  linkage-monitor/src/test/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitorTest.java
Labels: cla: yes

#984 testReadBom_path not to use boms/cloud-oss-bom/pom.xml
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/TestHelper.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
  dependencies/src/test/resources/libraries-bom-2.7.0.pom
Labels: cla: yes

#987 Apply Error Prone to all modules
  dependencies/pom.xml
  pom.xml
Labels: cla: yes

#989 Improve formatting of footer
  docs/_layouts/default.html
  docs/assets/css/style.css
Labels: cla: yes

#988 update gRPC to 1.24.1
  boms/cloud-oss-bom/pom.xml
Labels: cla: yes

#993 update maximum linkage errors test
  boms/integration-tests/src/test/java/com/google/cloud/MaximumLinkageErrorsTest.java
Labels: cla: yes

#996 Rewrite in active voice
  docs/JLBP-5.md
Labels: cla: yes

#995 Link to user docs for libraries-bom
  README.md
Labels: cla: yes

#997 MaximumlinakgeErrorsTest to automatically check with the latest version of the BOM
  boms/integration-tests/src/test/java/com/google/cloud/MaximumLinkageErrorsTest.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java
Labels: cla: yes

#1000 Add docs updates to the release instructions
  boms/cloud-oss-bom/RELEASING.md
Labels: cla: yes

#990 DependencyPath to hold scope and optional flag
  dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyTreeFormatter.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyPathTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyTreeFormatterTest.java
  linkage-monitor/src/test/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitorTest.java
Labels: cla: yes

#994 2.7.1 bom
  boms/cloud-oss-bom/pom.xml
  boms/upper-bounds-check/pom.xml
Labels: cla: yes

#1007 serve logo from Github pages
  docs/_layouts/default.html
  docs/assets/images/Cloud_Logo_Nav.svg
Labels: cla: yes

#1009 update google-http-java-client
  boms/cloud-oss-bom/pom.xml
Labels: cla: yes

#1010 2.8.0 bom
  boms/cloud-oss-bom/pom.xml
  boms/upper-bounds-check/pom.xml
Labels: cla: yes
