Repository GoogleCloudPlatform/cloud-opensource-java, pull requests merged in 2019-03, with the labels that each got.

#494 To fix dependency graph traversal order
  enforcer-rules/src/main/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRule.java
  enforcer-rules/src/test/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRuleTest.java
Labels: cla: yes

#486 Move main method of DependencyTreeFormatter to DependencyTreeFormatterMain
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyTreeFormatter.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyTreePrinter.java
Labels: cla: yes

#492 LinkageCheckerRule to have reachability option
  dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java
  enforcer-rules/README.md
  enforcer-rules/src/main/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRule.java
  enforcer-rules/src/test/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRuleTest.java
Labels: cla: yes

#502 no longer need maven home
  .circleci/config.yml
Labels: Tech Debt, Testing, cla: yes

#503 Renaming package, groupId and artifactId
  .circleci/config.yml
  dashboard/pom.xml
  dependencies/pom.xml
  enforcer-rules/README.md
  enforcer-rules/pom.xml
  enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java
  enforcer-rules/src/test/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRuleTest.java
  pom.xml
Labels: cla: yes

#506 Continuous build with Maven batch mode
  .circleci/config.yml
  kokoro/continuous.bat
Labels: cla: yes

#501 ignore .apt_generated directory
  .gitignore
Labels: cla: yes

#496 Not to load shadowed class file in a class path
  dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java
Labels: cla: yes

#507 guava-bom
  boms/cloud-oss-bom/pom.xml
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java
Labels: cla: yes

#515 update to latest Maven resolver and Guava
  pom.xml
Labels: cla: yes

#513 Add release scripts
  dependencies/kokoro/release_build.sh
  dependencies/kokoro/release_publish.sh
  dependencies/kokoro/release_sign.sh
  enforcer-rules/kokoro/release_build.sh
  enforcer-rules/kokoro/release_publish.sh
  enforcer-rules/kokoro/release_sign.sh
  kokoro/continuous.sh
  kokoro/parent_release_build.sh
  kokoro/parent_release_publish.sh
  kokoro/parent_release_sign.sh
  scripts/prepare_release.sh
Labels: cla: yes

#519 Updating version to 0.1.0-SNAPSHOT
  dashboard/pom.xml
  dependencies/pom.xml
  enforcer-rules/pom.xml
  pom.xml
Labels: cla: yes

#520 0.1.0 release preparation
  dashboard/pom.xml
  dependencies/pom.xml
  enforcer-rules/pom.xml
  pom.xml
Labels: cla: yes

#485 Read BOM via Path
  .circleci/config.yml
  README.md
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardArguments.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java
  dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/DashboardArgumentsTest.java
  dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/DashboardTest.java
  dependencies/pom.xml
  dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
  kokoro/ubuntu/periodic.sh
Labels: cla: yes

#523 Release step and reverting to version 0.1.0
  RELEASING.md
  dashboard/pom.xml
  dependencies/pom.xml
  enforcer-rules/pom.xml
  pom.xml
Labels: cla: yes

#517 added test that artifact exist in maven central
  dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/BomTest.java
Labels: cla: yes

#510 Adding DECLARING_DEPENDENCIES.md
  DECLARING_DEPENDENCIES.md
Labels: cla: yes

#531 <phase>process-classes</phase>
  enforcer-rules/README.md
Labels: cla: yes

#533 Recommend verify phase
  enforcer-rules/README.md
Labels: cla: yes

#534 Convert lambda to for loop so breakpoints can be set and single stepped
  enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java
Labels: cla: yes

#537 add google-http-java-client to BOM
  boms/cloud-oss-bom/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java
  dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/DashboardTest.java
  dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
Labels: cla: yes, enhancement

#544 Upgrade to latest 1.19.0
  boms/cloud-oss-bom/pom.xml
  dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/DashboardTest.java
Labels: cla: yes

#545 upgrade to latest google-cloud-java
  boms/cloud-oss-bom/pom.xml
  dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtilityTest.java
Labels: cla: yes

#547 more metadata for pom.xml
  dependencies/pom.xml
  enforcer-rules/pom.xml
  pom.xml
Labels: cla: yes
